spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
  #  mvc:
  #    static-path-pattern: /res/**
  #  resources:
  #    static-locations: [ classpath:/haha/ ]
  #    add-mappings: true
  #    cache:
  #      period: 11000
  web:
    resources:
      static-locations: [ classpath:/haha/ ]
      #Whether to enable default resource handling.
      add-mappings: true
      cache:
        period: 11000
#server:
#  servlet:
#    context-path: /world